"""Assemble enriched engineering blog articles into Obsidian markdown reports.

Reads two JSON files (fetched, enriched) from TMPDIR_ENGBLOGS,
merges them, and writes the ZH report, EN report, and Dashboard.
"""

import json
import os
import sys
from pathlib import Path


# ── Config ──────────────────────────────────────────────────────────

CATEGORY_EMOJI = {
    "ai-ml": "🤖",
    "infrastructure": "☁️",
    "data": "📊",
    "security": "🔒",
    "devtools": "🛠️",
    "platform": "⚙️",
    "research": "🔬",
    "other": "📌",
}

CATEGORY_LABEL = {
    "ai-ml": "AI / ML",
    "infrastructure": "Infrastructure",
    "data": "Data Engineering",
    "security": "Security",
    "devtools": "DevTools",
    "platform": "Platform",
    "research": "Research",
    "other": "Other",
}

RANK_EMOJI = {1: "1️⃣", 2: "2️⃣", 3: "3️⃣", 4: "4️⃣", 5: "5️⃣"}

CATEGORY_ORDER = ["ai-ml", "infrastructure", "platform", "data", "devtools", "security", "research", "other"]


def rank_str(rank: int) -> str:
    return RANK_EMOJI.get(rank, f"#{rank}")


def build_callout_zh(art: dict) -> str:
    cat_emoji = CATEGORY_EMOJI.get(art["category"], "📌")
    cat_label = CATEGORY_LABEL.get(art["category"], "Other")
    source = art.get("source_name", "")
    score = art.get("score", 0)
    new_badge = " · 🆕" if art.get("appearances", 0) == 0 else ""
    return f"""> [!tip] {rank_str(art["rank"])} {art["title"]}
> [{source}]({art["link"]}) · {cat_emoji} {cat_label} · ⭐ {score}/10{new_badge}
>
> {art["summary_zh"]}"""


def build_callout_en(art: dict) -> str:
    cat_emoji = CATEGORY_EMOJI.get(art["category"], "📌")
    cat_label = CATEGORY_LABEL.get(art["category"], "Other")
    source = art.get("source_name", "")
    score = art.get("score", 0)
    new_badge = " · 🆕" if art.get("appearances", 0) == 0 else ""
    return f"""> [!tip] {rank_str(art["rank"])} {art["title"]}
> [{source}]({art["link"]}) · {cat_emoji} {cat_label} · ⭐ {score}/10{new_badge}
>
> {art["summary_en"]}"""


def build_category_index(articles: list) -> str:
    cats: dict[str, list] = {}
    for art in articles:
        cats.setdefault(art["category"], []).append(art)

    sections = []
    for cat_key in CATEGORY_ORDER:
        if cat_key not in cats:
            continue
        emoji = CATEGORY_EMOJI[cat_key]
        label = CATEGORY_LABEL[cat_key]
        items = "\n".join(
            f"- [{a['title']}]({a['link']}) — {a.get('source_name', '')}"
            for a in cats[cat_key]
        )
        sections.append(f"## {emoji} {label}\n\n{items}")

    return "\n\n".join(sections)


def write_zh_report(articles: list, stats: dict, today: str, output_path: Path) -> None:
    count = len(articles)
    callouts = "\n\n".join(build_callout_zh(a) for a in articles)
    category_index = build_category_index(articles)

    sources_total = stats.get("sources_total", "?")
    articles_fetched = stats.get("articles_fetched", "?")

    report = f"""---
date: {today}
tags: [engineering-blogs, digest]
lang: zh
articles_scanned: {articles_fetched}
articles_selected: {count}
generator: claude-code
---

# 🏗️ Engineering Blogs — {today}

> 每日精选大厂工程博客 | Claude Code 生成
> English version: [[{today}-en]]

## 🏆 今日精选

{callouts}

---

## 📊 数据概览

| 来源 | 抓取 | 精选 |
|:---:|:---:|:---:|
| {sources_total} | {articles_fetched} | **{count}** |

---

{category_index}

---
*Generated by Claude Code*
"""
    output_path.write_text(report, encoding="utf-8")


def write_en_report(articles: list, stats: dict, today: str, output_path: Path) -> None:
    count = len(articles)
    callouts = "\n\n".join(build_callout_en(a) for a in articles)
    category_index = build_category_index(articles)

    sources_total = stats.get("sources_total", "?")
    articles_fetched = stats.get("articles_fetched", "?")

    report = f"""---
date: {today}
tags: [engineering-blogs, digest]
lang: en
articles_scanned: {articles_fetched}
articles_selected: {count}
generator: claude-code
---

# 🏗️ Engineering Blogs — {today}

> Daily curated engineering blog posts | Claude Code
> 中文版: [[{today}]]

## 🏆 Top Posts

{callouts}

---

## 📊 Stats

| Sources | Fetched | Selected |
|:---:|:---:|:---:|
| {sources_total} | {articles_fetched} | **{count}** |

---

{category_index}

---
*Generated by Claude Code*
"""
    output_path.write_text(report, encoding="utf-8")


def write_dashboard(today: str, feed_dir: Path) -> None:
    """Rebuild Dashboard.md from existing report files (last 14 days)."""
    dates = set()
    for f in feed_dir.glob("*.md"):
        name = f.stem
        if name == "Dashboard" or name.endswith("-en"):
            continue
        parts = name.split("-")
        if len(parts) == 3 and len(parts[0]) == 4:
            dates.add(name)

    sorted_dates = sorted(dates, reverse=True)[:14]
    if not sorted_dates:
        return

    latest = sorted_dates[0]
    rows = "\n".join(f"| {d} | [[{d}]] | [[{d}-en]] |" for d in sorted_dates)

    dashboard = f"""---
date: {today}
tags: [engineering-blogs, dashboard]
---

# Engineering Blogs

## Quick Links

- Latest: [[{latest}]]
- Latest (EN): [[{latest}-en]]

## Recent Reports

| Date | ZH | EN |
|------|----|----|
{rows}
"""
    (feed_dir / "Dashboard.md").write_text(dashboard, encoding="utf-8")


def main() -> None:
    tmpdir = os.environ["TMPDIR_ENGBLOGS"]
    today = os.environ["TODAY"]
    vault_dir = Path(os.environ["VAULT_DIR"])
    feed_dir = vault_dir / "Feeds" / "Engineering-Blogs"

    feed_dir.mkdir(parents=True, exist_ok=True)

    # Load inputs
    fetched = json.loads(Path(f"{tmpdir}/fetched.json").read_text())
    enriched = json.loads(Path(f"{tmpdir}/enriched.json").read_text())

    stats = fetched["stats"]
    enriched_list = enriched.get("enriched", enriched.get("articles", []))

    # Build lookup from fetched articles
    fetched_by_link: dict[str, dict] = {
        a["link"]: a for a in fetched.get("articles", [])
    }

    # Merge: start with fetched base, overlay enriched fields
    articles = []
    for i, art in enumerate(enriched_list, start=1):
        link = art.get("link", "")
        base = fetched_by_link.get(link, {})
        merged = {**base, **art}
        merged["rank"] = i
        merged.setdefault("summary_zh", "")
        merged.setdefault("summary_en", "")
        merged.setdefault("category", "other")
        articles.append(merged)

    print(f"[reports] Loaded {len(articles)} enriched articles", file=sys.stderr)

    # Write reports
    zh_path = feed_dir / f"{today}.md"
    write_zh_report(articles, stats, today, zh_path)
    print(f"[reports]   Wrote {zh_path}", file=sys.stderr)

    en_path = feed_dir / f"{today}-en.md"
    write_en_report(articles, stats, today, en_path)
    print(f"[reports]   Wrote {en_path}", file=sys.stderr)

    write_dashboard(today, feed_dir)
    print(f"[reports]   Wrote {feed_dir / 'Dashboard.md'}", file=sys.stderr)


if __name__ == "__main__":
    main()
