"""Assemble enriched GitHub trending repos into Obsidian markdown reports.

Reads two JSON files (fetched, enriched) from TMPDIR_TRENDING,
merges them, and writes the ZH report, EN report, and Dashboard.

This mirrors scripts/ai-digest/write_reports.py but adapted for GitHub repos.
"""

import json
import os
import sys
from pathlib import Path


# ── Config ──────────────────────────────────────────────────────────

CATEGORY_EMOJI = {
    "ai-ml": "🤖",
    "devtools": "🛠️",
    "web": "🌐",
    "systems": "⚙️",
    "data": "📊",
    "security": "🔒",
    "other": "📌",
}

CATEGORY_LABEL = {
    "ai-ml": "AI / ML",
    "devtools": "DevTools",
    "web": "Web",
    "systems": "Systems",
    "data": "Data",
    "security": "Security",
    "other": "Other",
}

RANK_EMOJI = {1: "🥇", 2: "🥈", 3: "🥉"}

CATEGORY_ORDER = ["ai-ml", "devtools", "web", "systems", "data", "security", "other"]


def rank_str(rank: int) -> str:
    return RANK_EMOJI.get(rank, f"#{rank}")


def source_badge(source: str) -> str:
    if source == "new":
        return "🆕 New"
    return "🔄 Active"


def build_callout_zh(repo: dict) -> str:
    cat_emoji = CATEGORY_EMOJI.get(repo["category"], "📌")
    cat_label = CATEGORY_LABEL.get(repo["category"], "Other")
    badge = source_badge(repo.get("source", "active"))
    topics = ", ".join(repo.get("topics", []))
    language = repo.get("language") or "—"
    stars = repo.get("stars", 0)
    return f"""> [!tip] {rank_str(repo["rank"])} {repo["full_name"]}  ⭐ {stars} · {language}
> [{repo["full_name"]}]({repo["url"]})
> {cat_emoji} {cat_label} · {badge}
>
> {repo["summary_zh"]}
>
> 🏷️ {topics}"""


def build_callout_en(repo: dict) -> str:
    cat_emoji = CATEGORY_EMOJI.get(repo["category"], "📌")
    cat_label = CATEGORY_LABEL.get(repo["category"], "Other")
    badge = source_badge(repo.get("source", "active"))
    topics = ", ".join(repo.get("topics", []))
    language = repo.get("language") or "—"
    stars = repo.get("stars", 0)
    return f"""> [!tip] {rank_str(repo["rank"])} {repo["full_name"]}  ⭐ {stars} · {language}
> [{repo["full_name"]}]({repo["url"]})
> {cat_emoji} {cat_label} · {badge}
>
> {repo["summary_en"]}
>
> 🏷️ {topics}"""


def build_category_index(repos: list, summary_key: str = "summary_en") -> str:
    """Build category index sections."""
    cats: dict[str, list] = {}
    for repo in repos:
        cats.setdefault(repo["category"], []).append(repo)

    sections = []
    for cat_key in CATEGORY_ORDER:
        if cat_key not in cats:
            continue
        emoji = CATEGORY_EMOJI[cat_key]
        label = CATEGORY_LABEL[cat_key]
        items = "\n".join(
            f"- [{r['full_name']}]({r['url']}) ⭐ {r.get('stars', 0)}"
            for r in cats[cat_key]
        )
        sections.append(f"## {emoji} {label}\n\n{items}")

    return "\n\n".join(sections)


def write_zh_report(repos: list, stats: dict, today: str, output_path: Path) -> None:
    count = len(repos)
    callouts = "\n\n".join(build_callout_zh(r) for r in repos)
    category_index = build_category_index(repos, summary_key="summary_zh")

    report = f"""---
date: {today}
tags: [github-trending, digest]
lang: zh
repos_scanned: {stats["after_dedup"]}
repos_selected: {count}
generator: claude-code
---

# 🔥 GitHub Trending — {today}

> 每日精选 GitHub 热门项目 | Claude Code 生成
> English version: [[{today}-en]]

## 🏆 今日热门

{callouts}

---

## 📊 数据概览

| 抓取 | 去重后 | 精选 |
|:---:|:---:|:---:|
| {stats["total_fetched"]} | {stats["after_dedup"]} | **{count}** |

---

{category_index}

---
*Generated by Claude Code*
"""
    output_path.write_text(report, encoding="utf-8")


def write_en_report(repos: list, stats: dict, today: str, output_path: Path) -> None:
    count = len(repos)
    callouts = "\n\n".join(build_callout_en(r) for r in repos)
    category_index = build_category_index(repos, summary_key="summary_en")

    report = f"""---
date: {today}
tags: [github-trending, digest]
lang: en
repos_scanned: {stats["after_dedup"]}
repos_selected: {count}
generator: claude-code
---

# 🔥 GitHub Trending — {today}

> Daily curated GitHub trending repos | Claude Code
> 中文版: [[{today}]]

## 🏆 Top Repos

{callouts}

---

## 📊 Stats

| Fetched | After Dedup | Selected |
|:---:|:---:|:---:|
| {stats["total_fetched"]} | {stats["after_dedup"]} | **{count}** |

---

{category_index}

---
*Generated by Claude Code*
"""
    output_path.write_text(report, encoding="utf-8")


def write_dashboard(today: str, feed_dir: Path) -> None:
    """Rebuild Dashboard.md from existing report files (last 14 days)."""
    dates = set()
    for f in feed_dir.glob("*.md"):
        name = f.stem
        if name == "Dashboard" or name.endswith("-en"):
            continue
        # Validate YYYY-MM-DD format
        parts = name.split("-")
        if len(parts) == 3 and len(parts[0]) == 4:
            dates.add(name)

    # Sort descending, take last 14
    sorted_dates = sorted(dates, reverse=True)[:14]

    if not sorted_dates:
        return

    latest = sorted_dates[0]
    rows = "\n".join(f"| {d} | [[{d}]] | [[{d}-en]] |" for d in sorted_dates)

    dashboard = f"""---
date: {today}
tags: [github-trending, dashboard]
---

# GitHub Trending

## Quick Links

- Latest: [[{latest}]]
- Latest (EN): [[{latest}-en]]

## Recent Reports

| Date | ZH | EN |
|------|----|----|
{rows}
"""
    (feed_dir / "Dashboard.md").write_text(dashboard, encoding="utf-8")


def main() -> None:
    tmpdir = os.environ["TMPDIR_TRENDING"]
    today = os.environ["TODAY"]
    vault_dir = Path(os.environ["VAULT_DIR"])
    feed_dir = vault_dir / "Feeds" / "GitHub-Trending"

    feed_dir.mkdir(parents=True, exist_ok=True)

    # Load inputs
    fetched = json.loads(Path(f"{tmpdir}/fetched.json").read_text())
    enriched = json.loads(Path(f"{tmpdir}/enriched.json").read_text())

    stats = fetched["stats"]

    # Build a lookup from enriched repos by full_name
    enriched_list = enriched.get("enriched", enriched.get("repos", []))
    enriched_by_name: dict[str, dict] = {
        r["full_name"]: r for r in enriched_list
    }

    # Merge: enriched list defines selection and ranking
    repos = []
    for i, repo in enumerate(enriched_list, start=1):
        full_name = repo["full_name"]
        # Start with raw fetch data if available, then overlay enriched fields
        base = enriched_by_name.get(full_name, {})
        merged = dict(base)
        merged["rank"] = i
        # Ensure required fields fall back gracefully
        merged.setdefault("summary_zh", "")
        merged.setdefault("summary_en", "")
        merged.setdefault("category", "other")
        merged.setdefault("topics", repo.get("topics", []))
        repos.append(merged)

    print(f"[reports] Loaded {len(repos)} enriched repos", file=sys.stderr)

    # Write reports
    zh_path = feed_dir / f"{today}.md"
    write_zh_report(repos, stats, today, zh_path)
    print(f"[reports]   Wrote {zh_path}", file=sys.stderr)

    en_path = feed_dir / f"{today}-en.md"
    write_en_report(repos, stats, today, en_path)
    print(f"[reports]   Wrote {en_path}", file=sys.stderr)

    write_dashboard(today, feed_dir)
    print(f"[reports]   Wrote {feed_dir / 'Dashboard.md'}", file=sys.stderr)


if __name__ == "__main__":
    main()
